# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0002_medicinecatetory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.MedicineCatetory')),
            ],
        ),
    ]
